@url = http://localhost:3000 

################################################################################################
####### Health Check Endpoint
################################################################################################

GET {{url}}/health
Content-Type: application/json

################################################################################################
####### Weather 
################################################################################################

GET {{url}}/api/v1/weather/today?latitude=39.7456&longitude=-97.0892
Content-Type: application/json
